feat: add getRecommendedFilms for films
EgorkaNazarov92/java-filmorate pull request #14
Opened 2024-07-23 22:01 UTC by iwfua

2024-07-23 22:34 UTC, ton1p requested changes

2024-07-23 22:34 UTC, ton1p commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +		return jdbc.query(FILMS_RECOMMENDED_QUERY, extractor, userId, userId);
findMany из супер класса

2024-07-24 07:31 UTC, EgorkaNazarov92 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> -    }
Мне кажется пропал метод

2024-07-24 07:37 UTC, EgorkaNazarov92 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> -    }
тут тоже удалился метод

2024-07-24 07:50 UTC, EgorkaNazarov92 approved these changes

2024-07-24 09:08 UTC, ton1p approved these changes

2024-07-24 09:12 UTC, merged